# This is a generated file. Not intended for manual editing.
services:
  evently.api:
    build:
      context: "D:\\Projects\\Evently"
      dockerfile: "src/API/Evently.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Evently.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "eventlyapi:dev"
    ports: []
    volumes:
    - "D:\\Projects\\Evently\\src\\API\\Evently.Api:/app:rw"
    - "D:\\Projects\\Evently:/src:rw"
    - "C:\\Users\\h.bakhshi\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
